wandb_version: 1

epochs:
  desc: null
  value: 2
learning_rate:
  desc: null
  value: <MagicMock name='mock.defaults.__getitem__()' id='131400670054496'>
batch_size:
  desc: null
  value: <MagicMock name='mock.batch_size' id='131400670058288'>
_wandb:
  desc: null
  value:
    python_version: 3.12.3
    cli_version: 0.17.4
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1723312110
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      2:
      - 1
      - 5
      - 53
      - 55
      3:
      - 13
      - 16
      - 23
      - 24
      4: 3.12.3
      5: 0.17.4
      8:
      - 5
      13: linux-x86_64
