wandb:
  project: ThyroidFNA_ClassAI
  name: "{time_stamp}_phase2_280824_valid_module1"
  description: |
    Phase 2: Valid Module 1
    # - Train Set: 70% of the data (not used)
    - Validation Set: 15% of the data
    # - Test Set: 15% of the data (not used)
      
data_para:
  data_dir: ./data/phase2_280824
  classes: ["B2", "B5", "B6"]
  num_workers: 20

evaluate_para:
  type: validation # validation or testing
  model_type: H0_EfficientNetB0
  model_name: phase2_280824_module1
  model_path: "{dir_path}/{model_path}"
  batch_size: 120
  seed: 97
  device: cuda

info_read:
  dir_path: ./results/{time_stamp}_{model_name}_{model_type}
  model_path: best_loss.pth

info_save:
  dir_path: "./results/{time_stamp}_{model_name}_{model_type}"
  evaluate_log: "{type}_log.csv"
  evaluate_confusion_matrix: "{type}_confusion_matrix.png"
  evaluate_roc_curve: "{type}_roc_curve.png"
  evaluate_classification_report: "{type}_classification_report.png"
