# configs/no_train_aug_no_val_aug/test_newdata241115_module1_efficientnet_b0_data_701515.yaml
tester:
  model_type: efficientnet_b0
  # model_path: "logs/1726492356_efficientnet_b0/best_f1_model.pth" # model su dung phuong phap moi
  model_path: "/Data/Projects/TempDataLogs_FromServer/1726428039_efficientnet_b0/best_f1_model.pth"
  # logs/1726492356_efficientnet_b0/best_loss_model.pth
  # test_data_path: "data/processed/1726417351_70_15_15_42/test"
  # test_data_path: "/Data/Projects/TempDataLogs_FromServer/data/processed/1726417351_70_15_15_42/test"
  # test_data_path: "/Data/Projects/TempDataLogs_FromServer/data/processed/1726417351_70_15_15_42/valid"
  # test_data_path: "/Data/Projects/TempDataLogs_FromServer/data/processed/1726417351_70_15_15_42/train"
  test_data_path: "data/newdata241115"
  batch_size: 120
  # device: cuda:0
  device: cpu
  test_logs_dir: "~/logs/test_module1_results/newdata241115"
  # test_logs_dir: "~/logs/test_1726417351_70_15_15_42"
