# configs/train_aug_no_val_aug/test_module1_efficientnet_b0_data_701515.yaml
tester:
  model_type: efficientnet_b0
  model_path: "logs/1726492356_efficientnet_b0/best_f1_model.pth"
  test_data_path: "data/processed/1726417351_70_15_15_42/test"
  batch_size: 120
  device: cuda:0
  test_logs_dir: "logs/test_module1_results/train_aug_no_val_aug"
