# configs/no_train_aug_no_val_aug/test_module1_vgg19_data_701515.yaml
tester:
  model_type: vgg19
  model_path: "logs/1726425303_vgg19/best_f1_model.pth"
  test_data_path: "data/processed/1726417351_70_15_15_42/test"
  device: cuda:0
  test_logs_dir: "logs/test_module1_results/no_train_aug_no_val_aug"
