trainer:
  model_type: "vgg16"                
  num_epochs: 100                       
  batch_size: 120                       
  patience: 10                         
  device: "cuda"   
  seed: 42                    
  lr: 0.0001                 
  
data:
  train_dir: "..."
  val_dir: "..."                  
  num_classes: 3
  augmentations:
    rotation: 15                     # Góc quay
    horizontal_flip: true            # Flip ngang
    vertical_flip: true              # Flip dọc
