# configs/experiment_44.yaml
type: "experiment"

experiment: "44"
name: "Retrain EfficientNetB7"

device: "cuda"

data:
  train_path:
    [
      "/home/haipn/data/dataver0/train",
      "/home/haipn/Research_ThyroidFNA_ClassAI/results/dataver1/train",
      "/home/haipn/Research_ThyroidFNA_ClassAI/results/dataver2_image/train",
      "/home/haipn/Research_ThyroidFNA_ClassAI/results/dataver2_patch/train",
    ]
  val_path:
    [
      "/home/haipn/data/dataver0/valid",
      "/home/haipn/Research_ThyroidFNA_ClassAI/results/dataver1/valid",
      "/home/haipn/Research_ThyroidFNA_ClassAI/results/dataver2_image/valid",
      "/home/haipn/Research_ThyroidFNA_ClassAI/results/dataver2_patch/valid",
    ]
  test_path:
    [
      "/home/haipn/data/dataver0/valid",
      "/home/haipn/Research_ThyroidFNA_ClassAI/results/dataver1/valid",
    ]
  num_workers: 20

model:
  type: "EfficientNetB7"
  dropout_rate: 0.1
  retrain_whole_net: true

training:
  batch_size: 20
  epochs: 100
  learning_rate: 0.0001
  optimizer: "adam"
  patience: 10
  save_path: "results/experiment_44/experiment_44.pth"

augmentation:
  horizontal_flip: true
  vertical_flip: true
  rotation_range: 20

classes: ["B2", "B5", "B6"]
seed: 42

logging:
  wandb: true
  project_name: "ThyroidFNA_ClassAI"
  run_name: "experiment 44: Retrain EfficientNetB7"
  save_path: "results/experiment_44"
