# configs/experiment_39.yaml
type: "experiment"

experiment: "39"
name: "Retrain EfficientNetB7"

device: "cuda"

data:
  train_path: ["/home/haipn/Research_ThyroidFNA_ClassAI/results/dataver1/train"]
  val_path: ["/home/haipn/Research_ThyroidFNA_ClassAI/results/dataver1/valid"]
  num_workers: 20

model:
  type: "EfficientNetB7"
  dropout_rate: 0.5
  retrain_whole_net: true

training:
  batch_size: 16
  epochs: 100
  learning_rate: 0.0001
  optimizer: "adam"
  patience: 10
  save_path: "results/experiment_39/experiment_39.pth"

augmentation:
  horizontal_flip: true
  vertical_flip: true
  rotation_range: 20

classes: ["B2", "B5", "B6"]
seed: 42

logging:
  wandb: true
  project_name: "ThyroidFNA_ClassAI"
  run_name: "experiment 39: Retrain EfficientNetB7"
  save_path: "results/experiment_39"
